sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t fxcasadei/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true fxcasadei/docker-react npm run test 